### ISSUE TITLE
Interest in new contributors?

### ISSUE THREAD

**Issue by stevenharman** [shairontoledo/rghost#72]
Hello! Thank you for RGhost. I love finding Gems that have been around as long as I have (in the Ruby community, I mean 😄). I too remember the great SVN to Git (and GitHub) migration.

I was wondering if you were open to new contributions? For example, I'd like to be able to render an PDF to an `IO` object, without having to write to a `File`.

And, in a more general sense, would you be OK with applying a consistent formatting to the project? I'm a fan if Standard.rb, mostly b/c we can delegate formatting and such to folks I trust to makes sensible, and minimal rules, while also getting consistency, thus reducing brain power needed to see/understand what the code is doing.

Anyhow, I'd like to contribute, but want to first understand what you're game to accept.

**Comment by shairontoledo** [comment]
@stevenharman I sent you an invite to be a collaborator. Game on and thumbs up for the IO implementation.

**Comment by stevenharman** [comment]
Great. I was going to spend a little time getting the lib up-to-date with current expectations for a Gem - things like having a `Gemfile` that loads the gemspec, declaring dev dependencies, file locations, etc… Then maybe `stardardrb` the whole thing? And maybe, _maybe_ get it running the tests via a GitHub Action.

How does that sound?

**Comment by stevenharman** [comment]
I just realized that there's no license defined in the `.gemspec`. Do you have a preferred license you'd want this under? I usually go with MIT, but I'd not presume that's your preference?

**Comment by shairontoledo** [comment]
Yes, MIT its the original license.
